# Generated by Django 3.2.11 on 2024-05-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atldump',
            options={'managed': True},
        ),
    ]
