# Generated by Django 3.2.11 on 2024-05-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_atldump_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='andinventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='andproperties',
            options={},
        ),
        migrations.AlterModelOptions(
            name='atldump',
            options={},
        ),
        migrations.AlterModelOptions(
            name='atlinventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='buyerssellers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemsdb',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemsdb2',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nycdump',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nycinventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nycproperties',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playerlocations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playerprofiles',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playerstats',
            options={},
        ),
        migrations.AlterModelOptions(
            name='travelroutes',
            options={},
        ),
    ]
